#!/usr/bin/env bash
set -euo pipefail

# Cross-build Mozc's Linux mozc_server with the Buildroot toolchain.
#
# This intentionally builds the conversion engine from source instead of
# importing a distro binary, so the resulting C++ runtime ABI matches the
# Scarlet Linux rootfs generated by Buildroot.
#
# Environment variables:
#  ARCH - target architecture (riscv64 or aarch64), defaults to aarch64
#  BUILDROOT_DIR - Buildroot tree; defaults to /opt/buildroot-$ARCH
#  PREBUILT_DIR - artifact staging directory, defaults to /opt/prebuilt
#  WORKDIR - checkout/build working directory, defaults to /opt
#  MOZC_REPO - Mozc source repository
#  MOZC_REV - optional branch, tag, or commit to check out
#  MOZC_DIR - Mozc checkout directory
#  MOZC_DICTIONARY - dictionary set to build with (oss or ut), defaults to oss
#  MOZC_UT_REPO - merge-ut-dictionaries source repository
#  MOZC_UT_REV - optional branch, tag, or commit to check out
#  MOZC_UT_DIR - merge-ut-dictionaries checkout directory
#  MOZC_UT_GENERATE_LATEST - generate latest UT dictionaries, defaults to 0
#  MOZC_HOST_PYTHON - host Python used for Mozc source patches and UT dictionary generation
#  MUSL_FTS_REPO - musl-fts source repository
#  MUSL_FTS_DIR - musl-fts checkout directory
#  MOZC_UPDATE_DEPS_ARGS - if set, run build_tools/update_deps.py with these arguments
#  MOZC_ALLOW_ROOT_SERVER - allow mozc_server to run as uid 0, defaults to 1
#  MOZC_TRACE_SERVER - print low-level mozc_server startup traces to stderr, defaults to 1
#  MOZC_BAZEL - bazel launcher, defaults to bazelisk if available
#  MOZC_BAZEL_EXTRA_ARGS - extra arguments passed before the target

: "${ARCH:=aarch64}"
: "${PREBUILT_DIR:=/opt/prebuilt}"
: "${WORKDIR:=/opt}"
: "${MOZC_REPO:=https://github.com/google/mozc.git}"
: "${MOZC_DICTIONARY:=oss}"
: "${MOZC_UT_REPO:=https://github.com/utuhiro78/merge-ut-dictionaries.git}"
: "${MOZC_UT_GENERATE_LATEST:=0}"
: "${MUSL_FTS_REPO:=https://github.com/void-linux/musl-fts.git}"
: "${MOZC_UPDATE_DEPS_ARGS:=}"
: "${MOZC_ALLOW_ROOT_SERVER:=1}"
: "${MOZC_TRACE_SERVER:=1}"
: "${MOZC_DIR:=${WORKDIR}/mozc-${ARCH}}"
: "${MOZC_UT_DIR:=${WORKDIR}/merge-ut-dictionaries}"
: "${MUSL_FTS_DIR:=${WORKDIR}/musl-fts}"

require_supported_host() {
    if [[ "$(uname -s)" != "Darwin" ]]; then
        return
    fi

    cat >&2 <<EOF
Mozc is built with Linux-host tooling and the Buildroot cross toolchain.
Run this script on Linux, such as scarlet-dev, a Linux VM, or a Linux Nix shell.

Example for AArch64 with repository-local paths:
  ARCH=aarch64 \\
  BUILDROOT_DIR="\$PWD/.scarlet/cache/buildroot-aarch64" \\
  PREBUILT_DIR="\$PWD/.scarlet/cache/prebuilt" \\
  WORKDIR="\$PWD/.scarlet/cache" \\
  bash tools/linux/build_mozc_server.sh
EOF
    exit 1
}

case "${ARCH}" in
    riscv64)
        : "${BUILDROOT_DIR:=/opt/buildroot}"
        TOOLCHAIN_PREFIX="riscv64-buildroot-linux-musl"
        BAZEL_CPU="riscv64"
        ;;
    aarch64)
        : "${BUILDROOT_DIR:=/opt/buildroot-aarch64}"
        TOOLCHAIN_PREFIX="aarch64-buildroot-linux-musl"
        BAZEL_CPU="aarch64"
        ;;
    *)
        echo "Unsupported ARCH=${ARCH}. Use riscv64 or aarch64." >&2
        exit 1
        ;;
esac

require_supported_host

if [[ ! -d "${BUILDROOT_DIR}" ]]; then
    echo "Expected buildroot directory at ${BUILDROOT_DIR} not found." >&2
    echo "Run ARCH=${ARCH} tools/linux/build_buildroot.sh first, or set BUILDROOT_DIR." >&2
    exit 1
fi

toolchain_bindir="${BUILDROOT_DIR}/output/host/bin"
toolchain_gcc="${toolchain_bindir}/${TOOLCHAIN_PREFIX}-gcc"
toolchain_gxx="${toolchain_bindir}/${TOOLCHAIN_PREFIX}-g++"
toolchain_ar="${toolchain_bindir}/${TOOLCHAIN_PREFIX}-ar"
toolchain_ranlib="${toolchain_bindir}/${TOOLCHAIN_PREFIX}-ranlib"
toolchain_strip="${toolchain_bindir}/${TOOLCHAIN_PREFIX}-strip"
toolchain_sysroot="${BUILDROOT_DIR}/output/host/${TOOLCHAIN_PREFIX}/sysroot"

for tool in "${toolchain_gcc}" "${toolchain_gxx}" "${toolchain_ar}" "${toolchain_ranlib}" "${toolchain_strip}"; do
    if [[ ! -x "${tool}" ]]; then
        echo "Buildroot toolchain component missing: ${tool}" >&2
        echo "Run ARCH=${ARCH} tools/linux/build_buildroot.sh first." >&2
        exit 1
    fi
done

if [[ ! -d "${toolchain_sysroot}" ]]; then
    echo "Buildroot sysroot missing at ${toolchain_sysroot}." >&2
    exit 1
fi

find_host_python() {
    local candidate

    while IFS= read -r candidate; do
        if [[ -x "${candidate}" ]] && "${candidate}" -c 'import bz2' >/dev/null 2>&1; then
            echo "${candidate}"
            return
        fi
    done < <(which -a python3 2>/dev/null || true)
}

if [[ -z "${MOZC_HOST_PYTHON:-}" ]]; then
    MOZC_HOST_PYTHON="$(find_host_python)"
fi
if [[ -z "${MOZC_HOST_PYTHON}" || ! -x "${MOZC_HOST_PYTHON}" ]]; then
    echo "Host python3 with bz2 support is not available." >&2
    echo "Set MOZC_HOST_PYTHON=/path/to/python3." >&2
    exit 1
fi
if ! "${MOZC_HOST_PYTHON}" -c 'import bz2' >/dev/null 2>&1; then
    echo "Host Python at ${MOZC_HOST_PYTHON} cannot import bz2." >&2
    echo "Set MOZC_HOST_PYTHON to a Python with bz2 support." >&2
    exit 1
fi

export PATH="${toolchain_bindir}:${PATH}"

if [[ -z "${MOZC_BAZEL:-}" ]]; then
    if command -v bazelisk >/dev/null 2>&1; then
        MOZC_BAZEL="bazelisk"
    elif command -v bazel >/dev/null 2>&1; then
        MOZC_BAZEL="bazel"
    else
        echo "Neither bazelisk nor bazel is available." >&2
        echo "Install bazelisk, or set MOZC_BAZEL=/path/to/bazel." >&2
        exit 1
    fi
fi

clone_or_update() {
    local repo_url="$1"
    local dest_dir="$2"

    if [[ -d "${dest_dir}/.git" ]]; then
        git -C "${dest_dir}" fetch --depth=1 origin
    else
        git clone --depth=1 "${repo_url}" "${dest_dir}"
    fi
}

checkout_optional_rev() {
    local dest_dir="$1"
    local rev="$2"

    if [[ -z "${rev}" ]]; then
        return
    fi

    git -C "${dest_dir}" fetch --depth=1 origin "${rev}" || true
    git -C "${dest_dir}" checkout "${rev}"
}

build_musl_fts_if_needed() {
    if [[ -f "${toolchain_sysroot}/usr/include/fts.h" && -f "${toolchain_sysroot}/usr/lib/libfts.a" ]]; then
        return
    fi

    echo "==> Building musl-fts for ${ARCH}..."
    clone_or_update "${MUSL_FTS_REPO}" "${MUSL_FTS_DIR}"

    pushd "${MUSL_FTS_DIR}" >/dev/null
    ./bootstrap.sh
    ./configure \
        --host="${TOOLCHAIN_PREFIX}" \
        --prefix="${MUSL_FTS_DIR}/install-${ARCH}" \
        "CC=${toolchain_gcc}" \
        "AR=${toolchain_ar}" \
        "RANLIB=${toolchain_ranlib}"
    make -j "$(nproc)"
    make install
    popd >/dev/null

    mkdir -p "${toolchain_sysroot}/usr/include" "${toolchain_sysroot}/usr/lib"
    cp "${MUSL_FTS_DIR}/install-${ARCH}/include/fts.h" "${toolchain_sysroot}/usr/include/fts.h"
    cp "${MUSL_FTS_DIR}/install-${ARCH}/lib/libfts.a" "${toolchain_sysroot}/usr/lib/libfts.a"
    "${toolchain_ranlib}" "${toolchain_sysroot}/usr/lib/libfts.a"
}

ensure_host_can_run_target_musl_tools() {
    case "${ARCH}:$(uname -m)" in
        aarch64:aarch64 | aarch64:arm64)
            local loader="/lib/ld-musl-aarch64.so.1"
            local libc="${toolchain_sysroot}/lib/libc.so"
            local libgcc="${toolchain_sysroot}/lib/libgcc_s.so.1"
            local libstdcxx="${toolchain_sysroot}/usr/lib/libstdc++.so.6"

            if [[ ! -e "${loader}" && -w /lib ]]; then
                ln -sf "${libc}" "${loader}"
            fi
            if [[ ! -e /lib/libc.so && -w /lib ]]; then
                ln -sf "${libc}" /lib/libc.so
            fi
            if [[ ! -e /lib/libgcc_s.so.1 && -w /lib ]]; then
                ln -sf "${libgcc}" /lib/libgcc_s.so.1
            fi
            if [[ ! -e /lib/libstdc++.so.6 && -w /lib ]]; then
                ln -sf "${libstdcxx}" /lib/libstdc++.so.6
            fi

            if [[ ! -e "${loader}" ]]; then
                echo "Target musl loader missing: ${loader}" >&2
                echo "Bazel needs to run generated ${ARCH} tools during the build." >&2
                exit 1
            fi
            ;;
    esac
}

build_musl_fts_if_needed
ensure_host_can_run_target_musl_tools

echo "==> Fetching Mozc source..."
clone_or_update "${MOZC_REPO}" "${MOZC_DIR}"
checkout_optional_rev "${MOZC_DIR}" "${MOZC_REV:-}"

src_dir="${MOZC_DIR}/src"
if [[ ! -d "${src_dir}" ]]; then
    echo "Mozc source directory not found at ${src_dir}" >&2
    exit 1
fi

prepare_dictionary() {
    local dictionary_file="${src_dir}/data/dictionary_oss/dictionary00.txt"
    local merge_dir="${MOZC_UT_DIR}/src/merge"
    local expected_mozc_link

    if [[ ! -f "${dictionary_file}" ]]; then
        echo "Mozc OSS dictionary was not found at ${dictionary_file}" >&2
        exit 1
    fi

    # The Mozc checkout is a script-owned working tree. Restore the base OSS
    # dictionary before each build so repeated UT builds do not append twice.
    git -C "${MOZC_DIR}" checkout -- src/data/dictionary_oss/dictionary00.txt

    case "${MOZC_DICTIONARY}" in
        oss)
            echo "==> Using Mozc OSS dictionary."
            return
            ;;
        ut)
            ;;
        *)
            echo "Unsupported MOZC_DICTIONARY=${MOZC_DICTIONARY}. Use oss or ut." >&2
            exit 1
            ;;
    esac

    echo "==> Fetching merge-ut-dictionaries..."
    clone_or_update "${MOZC_UT_REPO}" "${MOZC_UT_DIR}"
    checkout_optional_rev "${MOZC_UT_DIR}" "${MOZC_UT_REV:-}"

    if [[ ! -d "${merge_dir}" ]]; then
        echo "merge-ut-dictionaries merge directory not found at ${merge_dir}" >&2
        exit 1
    fi
    git -C "${MOZC_UT_DIR}" checkout -- src/merge/make.sh

    "${MOZC_HOST_PYTHON}" - "${merge_dir}/make.sh" "${MOZC_HOST_PYTHON}" <<'PY'
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
host_python = sys.argv[2]
text = path.read_text()
text = text.replace(
    'python merge_dictionaries.py mozcdic-ut.txt',
    f'"{host_python}" merge_dictionaries.py mozcdic-ut.txt',
)
path.write_text(text)
PY

    expected_mozc_link="$(dirname "${MOZC_UT_DIR}")/mozc-master"
    if [[ -e "${expected_mozc_link}" && ! -L "${expected_mozc_link}" ]]; then
        echo "Expected ${expected_mozc_link} to be absent or a symlink." >&2
        echo "Set MOZC_UT_DIR so merge-ut-dictionaries can see Mozc as ../mozc-master." >&2
        exit 1
    fi
    ln -sfn "${MOZC_DIR}" "${expected_mozc_link}"

    if [[ "${MOZC_UT_GENERATE_LATEST}" == "1" ]]; then
        "${MOZC_HOST_PYTHON}" - "${merge_dir}/make.sh" <<'PY'
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
text = path.read_text()
path.write_text(text.replace('#generate_latest="true"', 'generate_latest="true"'))
PY
    fi

    echo "==> Generating Mozc UT dictionary..."
    pushd "${merge_dir}" >/dev/null
    PATH="$(dirname "${MOZC_HOST_PYTHON}"):${PATH}" bash make.sh
    popd >/dev/null

    if [[ ! -f "${merge_dir}/mozcdic-ut.txt" ]]; then
        echo "Mozc UT dictionary was not produced at ${merge_dir}/mozcdic-ut.txt" >&2
        exit 1
    fi

    echo "==> Merging Mozc UT dictionary into Mozc OSS dictionary..."
    cat "${merge_dir}/mozcdic-ut.txt" >> "${dictionary_file}"
}

prepare_dictionary

if [[ "${MOZC_ALLOW_ROOT_SERVER}" == "1" ]]; then
    run_level_cc="${src_dir}/base/run_level.cc"
    if ! grep -q "Scarlet Linux ABI runs mozc_server as uid 0" "${run_level_cc}"; then
        "${MOZC_HOST_PYTHON}" - "${run_level_cc}" <<'PY'
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
text = path.read_text()
old = """  if (type == SERVER || type == RENDERER) {
    if (::geteuid() == 0) {
      // This process is started by root, or the executable is setuid to root.

      // TODO(yusukes): It would be better to add 'SAFE' run-level which
      //  prohibits all mutable operations to local resources and return the
      //  level after calling chroot(\"/somewhere/safe\"), setgid(\"nogroup\"),
      //  and setuid(\"nobody\") here. This is because many novice Linux users
      //  tend to login to their desktop as root.

      return RunLevel::DENY;
    }
    if (::getuid() == 0) {
      // The executable is setuided to non-root and is started by root user?
      // This is unexpected. Returns DENY.
      return RunLevel::DENY;
    }
    return RunLevel::NORMAL;
  }
"""
new = """  if (type == SERVER || type == RENDERER) {
    if (::geteuid() == 0 || ::getuid() == 0) {
      // Scarlet Linux ABI runs mozc_server as uid 0 for now.
      return RunLevel::NORMAL;
    }
    return RunLevel::NORMAL;
  }
"""
if old not in text:
    raise SystemExit("Mozc run_level.cc root run-level block was not found")
path.write_text(text.replace(old, new))
PY
    fi
fi

if [[ "${MOZC_TRACE_SERVER}" == "1" ]]; then
    server_cc="${src_dir}/server/mozc_server.cc"
    if ! grep -q "ScarletTrace" "${server_cc}"; then
        "${MOZC_HOST_PYTHON}" - "${server_cc}" <<'PY'
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
text = path.read_text()
text = text.replace(
    "#include <bit>\n#include <memory>\n#include <string>\n",
    "#include <bit>\n#include <cstring>\n#include <memory>\n#include <string>\n\n#include <unistd.h>\n",
)
text = text.replace(
    "namespace {\nmozc::SessionServer *g_session_server = nullptr;\n}\n",
    """namespace {
mozc::SessionServer *g_session_server = nullptr;

void ScarletTrace(const char *message) {
  ::write(STDERR_FILENO, message, std::strlen(message));
}
}  // namespace
""",
)
text = text.replace(
    "void InitMozcAndMozcServer(const char *arg0, int *argc, char ***argv,\n                           bool remove_flags) {\n",
    "void InitMozcAndMozcServer(const char *arg0, int *argc, char ***argv,\n                           bool remove_flags) {\n  ScarletTrace(\"[mozc_server] init start\\n\");\n",
)
text = text.replace(
    "  if (run_level >= mozc::RunLevel::DENY) {\n    LOG(FATAL) << \"Do not execute Mozc server as high authority\";\n",
    "  if (run_level >= mozc::RunLevel::DENY) {\n    ScarletTrace(\"[mozc_server] run level denied\\n\");\n    LOG(FATAL) << \"Do not execute Mozc server as high authority\";\n",
)
text = text.replace(
    "  mozc::InitMozc(arg0, argc, argv);\n",
    "  mozc::InitMozc(arg0, argc, argv);\n  ScarletTrace(\"[mozc_server] InitMozc done\\n\");\n",
)
text = text.replace(
    "int MozcServer::Run() {\n",
    "int MozcServer::Run() {\n  ScarletTrace(\"[mozc_server] Run start\\n\");\n",
)
text = text.replace(
    "  if (!mutex.Lock()) {\n    LOG(INFO) << \"Mozc Server is already running\";\n",
    "  if (!mutex.Lock()) {\n    ScarletTrace(\"[mozc_server] mutex lock failed\\n\");\n    LOG(INFO) << \"Mozc Server is already running\";\n",
)
text = text.replace(
    "  {\n    std::unique_ptr<mozc::SessionServer> session_server =\n",
    "  ScarletTrace(\"[mozc_server] mutex locked\\n\");\n\n  {\n    ScarletTrace(\"[mozc_server] creating SessionServer\\n\");\n    std::unique_ptr<mozc::SessionServer> session_server =\n",
)
text = text.replace(
    "    if (!g_session_server->Connected()) {\n      LOG(ERROR) << \"SessionServer initialization failed\";\n",
    "    if (!g_session_server->Connected()) {\n      ScarletTrace(\"[mozc_server] SessionServer not connected\\n\");\n      LOG(ERROR) << \"SessionServer initialization failed\";\n",
)
text = text.replace(
    "#else   // defined(_WIN32)\n    // Create a new thread.\n",
    "#else   // defined(_WIN32)\n    ScarletTrace(\"[mozc_server] SessionServer connected\\n\");\n    // Create a new thread.\n",
)
text = text.replace(
    "    g_session_server->LoopAndReturn();\n\n    // Wait until the session server thread finishes.\n    g_session_server->Wait();\n",
    "    ScarletTrace(\"[mozc_server] LoopAndReturn\\n\");\n    g_session_server->LoopAndReturn();\n\n    // Wait until the session server thread finishes.\n    ScarletTrace(\"[mozc_server] Wait\\n\");\n    g_session_server->Wait();\n    ScarletTrace(\"[mozc_server] Wait returned\\n\");\n",
)
text = text.replace(
    "  return 0;\n}\n\nint MozcServer::Finalize() {\n",
    "  ScarletTrace(\"[mozc_server] Run returning 0\\n\");\n  return 0;\n}\n\nint MozcServer::Finalize() {\n",
)
path.write_text(text)
PY
    fi

    unix_ipc_cc="${src_dir}/ipc/unix_ipc.cc"
    if ! grep -q "ScarletIPCTrace" "${unix_ipc_cc}"; then
        "${MOZC_HOST_PYTHON}" - "${unix_ipc_cc}" <<'PY'
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
text = path.read_text()
text = text.replace(
    "constexpr int kInvalidSocket = -1;\n",
    """constexpr int kInvalidSocket = -1;

void ScarletIPCTrace(const char *message) {
  ::write(STDERR_FILENO, message, std::strlen(message));
}
""",
)
text = text.replace(
    "IPCServer::IPCServer(absl::string_view name, int32_t num_connections,\n                     absl::Duration timeout)\n",
    "IPCServer::IPCServer(absl::string_view name, int32_t num_connections,\n                     absl::Duration timeout)\n",
)
text = text.replace(
    "      socket_(kInvalidSocket),\n      timeout_(timeout) {\n",
    "      socket_(kInvalidSocket),\n      timeout_(timeout) {\n  ScarletIPCTrace(\"[mozc_server] IPCServer ctor\\n\");\n",
)
text = text.replace(
    "  if (!manager->CreateNewPathName() && !manager->LoadPathName()) {\n    LOG(ERROR) << \"Cannot prepare IPC path name\";\n",
    "  if (!manager->CreateNewPathName() && !manager->LoadPathName()) {\n    ScarletIPCTrace(\"[mozc_server] IPC path prepare failed\\n\");\n    LOG(ERROR) << \"Cannot prepare IPC path name\";\n",
)
text = text.replace(
    "  if (!manager->GetPathName(&server_address_)) {\n    LOG(ERROR) << \"Cannot make IPC path name\";\n",
    "  if (!manager->GetPathName(&server_address_)) {\n    ScarletIPCTrace(\"[mozc_server] IPC path name failed\\n\");\n    LOG(ERROR) << \"Cannot make IPC path name\";\n",
)
text = text.replace(
    "  socket_ = ::socket(PF_UNIX, SOCK_STREAM, 0);\n",
    "  ScarletIPCTrace(\"[mozc_server] socket\\n\");\n  socket_ = ::socket(PF_UNIX, SOCK_STREAM, 0);\n",
)
text = text.replace(
    "  if (socket_ < 0) {\n    LOG(WARNING) << \"socket failed: \" << strerror(errno);\n",
    "  if (socket_ < 0) {\n    ScarletIPCTrace(\"[mozc_server] socket failed\\n\");\n    LOG(WARNING) << \"socket failed: \" << strerror(errno);\n",
)
text = text.replace(
    "  if (::bind(socket_, reinterpret_cast<sockaddr *>(&addr), sun_len) != 0) {\n",
    "  ScarletIPCTrace(\"[mozc_server] bind\\n\");\n  if (::bind(socket_, reinterpret_cast<sockaddr *>(&addr), sun_len) != 0) {\n",
)
text = text.replace(
    "    LOG(FATAL) << \"bind() failed: \" << strerror(errno);\n",
    "    ScarletIPCTrace(\"[mozc_server] bind failed\\n\");\n    LOG(FATAL) << \"bind() failed: \" << strerror(errno);\n",
)
text = text.replace(
    "  if (::listen(socket_, num_connections) < 0) {\n",
    "  ScarletIPCTrace(\"[mozc_server] listen\\n\");\n  if (::listen(socket_, num_connections) < 0) {\n",
)
text = text.replace(
    "    LOG(FATAL) << \"listen() failed: \" << strerror(errno);\n",
    "    ScarletIPCTrace(\"[mozc_server] listen failed\\n\");\n    LOG(FATAL) << \"listen() failed: \" << strerror(errno);\n",
)
text = text.replace(
    "  if (!manager->SavePathName()) {\n    LOG(ERROR) << \"Cannot save IPC path name\";\n",
    "  if (!manager->SavePathName()) {\n    ScarletIPCTrace(\"[mozc_server] save IPC path failed\\n\");\n    LOG(ERROR) << \"Cannot save IPC path name\";\n",
)
text = text.replace(
    "  connected_ = true;\n",
    "  connected_ = true;\n  ScarletIPCTrace(\"[mozc_server] IPCServer connected\\n\");\n",
)
text = text.replace(
    "void IPCServer::Loop() {\n",
    "void IPCServer::Loop() {\n  ScarletIPCTrace(\"[mozc_server] IPCServer Loop start\\n\");\n",
)
text = text.replace(
    "    const int new_sock = ::accept(socket_, nullptr, nullptr);\n",
    "    ScarletIPCTrace(\"[mozc_server] accept\\n\");\n    const int new_sock = ::accept(socket_, nullptr, nullptr);\n",
)
text = text.replace(
    "      LOG(FATAL) << \"accept() failed: \" << strerror(errno);\n",
    "      ScarletIPCTrace(\"[mozc_server] accept failed\\n\");\n      LOG(FATAL) << \"accept() failed: \" << strerror(errno);\n",
)
text = text.replace(
    "  connected_ = false;\n",
    "  ScarletIPCTrace(\"[mozc_server] IPCServer Loop end\\n\");\n  connected_ = false;\n",
    1,
)
path.write_text(text)
PY
    fi
fi

pushd "${src_dir}" >/dev/null
if [[ -n "${MOZC_UPDATE_DEPS_ARGS}" ]]; then
    echo "==> Updating Mozc dependencies..."
    # shellcheck disable=SC2086
    "${MOZC_HOST_PYTHON}" build_tools/update_deps.py ${MOZC_UPDATE_DEPS_ARGS}
fi

mkdir -p "${WORKDIR}/bazel-${ARCH}"

build_args=(
    "--output_user_root=${WORKDIR}/bazel-${ARCH}"
    "build"
    "--config=oss_linux"
    "--config=release_build"
    "--cpu=${BAZEL_CPU}"
    "--crosstool_top=@local_config_cc//:toolchain"
    "--host_crosstool_top=@bazel_tools//tools/cpp:toolchain"
    "--repo_env=CC=${toolchain_gcc}"
    "--repo_env=CXX=${toolchain_gxx}"
    "--action_env=CC=${toolchain_gcc}"
    "--action_env=CXX=${toolchain_gxx}"
    "--action_env=AR=${toolchain_ar}"
    "--action_env=STRIP=${toolchain_strip}"
    "--copt=--sysroot=${toolchain_sysroot}"
    "--cxxopt=--sysroot=${toolchain_sysroot}"
    "--linkopt=--sysroot=${toolchain_sysroot}"
    "--linkopt=-Wl,-rpath-link,${toolchain_sysroot}/usr/lib"
    "--linkopt=-Wl,-rpath-link,${toolchain_sysroot}/lib"
    "--linkopt=-lfts"
    "--host_linkopt=-lfts"
)

if [[ -n "${MOZC_BAZEL_EXTRA_ARGS:-}" ]]; then
    # shellcheck disable=SC2206
    extra_args=(${MOZC_BAZEL_EXTRA_ARGS})
    build_args+=("${extra_args[@]}")
fi

build_args+=("//server:mozc_server")

echo "==> Building mozc_server for ${ARCH} with Buildroot toolchain..."
echo "    CC=${toolchain_gcc}"
echo "    CXX=${toolchain_gxx}"
"${MOZC_BAZEL}" "${build_args[@]}"

if [[ ! -f "bazel-bin/server/mozc_server" ]]; then
    echo "bazel-bin/server/mozc_server was not produced." >&2
    exit 1
fi

stage_dir="${PREBUILT_DIR}/${ARCH}/root/usr/lib/mozc"
mkdir -p "${stage_dir}"
"${toolchain_strip}" -o "${stage_dir}/mozc_server" "bazel-bin/server/mozc_server"
chmod +x "${stage_dir}/mozc_server"
popd >/dev/null

echo ""
echo "==> Mozc server built successfully!"
echo "    Binary: ${stage_dir}/mozc_server"
echo "    ABI:    ${ARCH} musl via Buildroot"
echo ""
echo "Deploy with:"
echo "  ARCH=${ARCH} PREBUILT_DIR=${PREBUILT_DIR} bash tools/linux/deploy_rootfs.sh"
